# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8xiKPajfcvYItcifOsIN_IcI70PO51j
"""



"""##Resolución problema##"""



"""$$\lim _{x\to 4}\left(\frac{x-4}{x^2-16}\right)$$"""

from sympy import *
x = symbols('x')



"""Definir expresión"""

expr = (x-4)/(x**2-16)

"""Gráfico la función:"""

import matplotlib.pyplot as plt
import numpy as np

f = lambdify(x, expr, "numpy")
x_vals = np.linspace(3.5, 4.5, 1000)
y_vals = f(x_vals)
plt.plot(x_vals, y_vals)
plt.axhline(y=0, color='k', lw=0.5)
plt.axvline(x=4, color='k', lw=0.5)
plt.ylim([-10, 10])
plt.title("Gráfico de la función")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

""" la función se acerca a un límite cuando x se acerca a 4"""



"""Simplificar la expresión"""

simplified_expr = simplify(expr)
simplified_expr

"""La expresión simplificada es:"""

1/(x+4)

"""Evaluar el límite"""

limit_expr = limit(expr, x, 4)
limit_expr

"""El resultado es "oo", lo que significa que el límite es infinito.

Analizar los límites laterales
"""

left_limit = limit(expr, x, 4, dir='-')
right_limit = limit(expr, x, 4, dir='+')
print(f"Límite por la izquierda: {left_limit}")
print(f"Límite por la derecha: {right_limit}")

"""El límite por la izquierda es "-oo" y el límite por la derecha es "+oo", lo que significa que los límites laterales no son iguales.

Conclusión:
"""

print("El límite no existe.")